name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  my-jobs2:
    runs-on: ubuntu-letest
    steps:
      - name: my step
        run: echo "Hello agine"